### ISSUE TITLE
Followed the instructions and deployed GCloud functions but no commands added to my discord server

### ISSUE THREAD

**Issue by mrbaguettefr** [jdamour98/discord-gcloud-commands#2]
1/ I authorized my application:

2/ I used gcloud CLI to deploy (after modifing package.json etc..):
`gcloud --project=factorio-bcc functions deploy factorio-bcc-gcloud-bot --allow-unauthenticated --memory=128MiB --timeout=60 --trigger-http --region=europe-west1 --runtime=nodejs14 --env-vars-file=.env.yaml --entry-point=interactions --source=.`

.env.yaml:
```
DISCORD_APPLICATION_ID: "890586780645097542"
DISCORD_PUBLIC_KEY: "070f8a381e9f8af1321d40b233336cd3ce86d97559aa609f4686e2b9ca0fab7a"
DISCORD_TOKEN: "redacted"
DISCORD_GUILD_ID: "668547917589774336"
GCLOUD_PROJECT: "factorio-bcc"
DEFAULT_COMPUTE_ZONE: "europe-west1-b"
USER_ROLE_ID: "779463074511716393"
MANAGER_ROLE_ID: "889044253668421682"
```

Function is deployed and running.

Though I don't see any new commands (I added the GUILD_ID so it should be instant right?)

Note: I see one request with resulted in a HTTP 200 status but then another one ending with an 401 error in the function logs, nothing else.

Any thoughts?

**Comment by jasondamour** [comment]
The 401 is almost certainly the root cause, and the error message can tell use more. Can you post the entire logs?

Additionally, slash-create has released a couple major changes since I published this repo, and I don't think my code is up to date. Particularly, I think the way guild IDs are passed to the slash create object has changed. What version of slash-create are you using? Can you post your snippet where you pass guild id to the slash-create object?

**Comment by mrbaguettefr** [comment]
It was on my side. I did not understand that I still have to create a bot user. I got confused with the Discord documentation about Slash commands, saying I don't need a bot.

IT works perfectly!!
