### ISSUE TITLE
No autocomplete commands appearing on the sever.

### ISSUE THREAD

**Issue by crocokyle** [jdamour98/discord-gcloud-commands#5]
I've got a fork of your repo here: https://github.com/crocokyle/discord-gcp-bot

I've tried both the Google Cloud Functions and Google Cloud Run implementations. I've gotten the function and container running without any issues but am not seeing the commands in my autocomplete in the discord server. 

Here is the file tree I've got in the Cloud Functions implementation: 
![image](https://user-images.githubusercontent.com/11140843/163689377-8f895b65-2bd4-48e0-87e3-21fcda40d099.png)

I'm using the Entry point "interactions". 

There aren't errors or warnings in the logs. Any recommendations?

**Comment by saladbar15** [comment]
I know this is months later, but I found the issue for me to be the DISCORD_TOKEN variable. Instead of Client Secret, this needed to be the Bot Token.

Was tipped off by this change based on the documentation here: https://slash-create.js.org/#/docs/main/latest/examples/basic

With that changed, the slash commands published to Discord as expected.
